spring:
  application:
    name: lgn

server:
  port: 8099

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
feign:
    hystrix:
        enabled: true
    